"""create database

Revision ID: 4e0cfa6d0637
Revises: 
Create Date: 2024-05-19 15:59:46.076838

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e0cfa6d0637"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "replacements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("current_value", sa.String(), nullable=False),
        sa.Column("replace", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("current_value"),
        sa.UniqueConstraint("replace"),
    )
    op.create_table(
        "urls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("urls")
    op.drop_table("replacements")
    # ### end Alembic commands ###
